"""add document_authors association table for multi-author documents

Revision ID: 2555f3669cea
Revises: 29825109273b
Create Date: 2026-07-30 16:49:51.150686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2555f3669cea'
down_revision: Union[str, Sequence[str], None] = '29825109273b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_authors',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'author_id')
    )

    # Backfill: every existing document's single author_id becomes its first
    # row in the association table before the column is dropped.
    op.execute(
        "INSERT INTO document_authors (document_id, author_id) "
        "SELECT id, author_id FROM documents"
    )

    op.drop_index(op.f('ix_documents_author_id'), table_name='documents')
    op.drop_constraint(op.f('uq_document_author_content_hash'), 'documents', type_='unique')
    op.drop_constraint(op.f('uq_document_author_filename'), 'documents', type_='unique')
    op.create_unique_constraint('uq_document_content_hash', 'documents', ['content_hash'])
    op.drop_constraint(op.f('documents_author_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('author_id', sa.INTEGER(), autoincrement=True, nullable=True))

    # Lossy: a document credited to more than one author can only keep one
    # author_id on the way back down, so we pick the lowest author id.
    op.execute(
        "UPDATE documents SET author_id = ("
        "SELECT MIN(author_id) FROM document_authors "
        "WHERE document_authors.document_id = documents.id"
        ")"
    )

    op.alter_column('documents', 'author_id', nullable=False)
    op.create_foreign_key(op.f('documents_author_id_fkey'), 'documents', 'authors', ['author_id'], ['id'])
    op.drop_constraint('uq_document_content_hash', 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_document_author_filename'), 'documents', ['author_id', 'filename'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_document_author_content_hash'), 'documents', ['author_id', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_documents_author_id'), 'documents', ['author_id'], unique=False)
    op.drop_table('document_authors')
    # ### end Alembic commands ###
