"""add cached stylometric stats to documents

Revision ID: 3ed227125c5c
Revises: 2555f3669cea
Create Date: 2026-08-04 15:56:20.917023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed227125c5c'
down_revision: Union[str, Sequence[str], None] = '2555f3669cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('token_counts', sa.JSON(), nullable=False))
    op.add_column('documents', sa.Column('sentence_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('total_sentence_word_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_sentence_word_count')
    op.drop_column('documents', 'sentence_count')
    op.drop_column('documents', 'token_counts')
    # ### end Alembic commands ###
