"""create author style profiles table

Revision ID: 8ed256c8c1de
Revises: 8e6fec04f3c4
Create Date: 2026-07-21 17:25:46.221560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed256c8c1de'
down_revision: Union[str, Sequence[str], None] = '8e6fec04f3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('profile_vector', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('num_documents_used', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'feature_type', 'model_version', name='uq_author_style_profile_triple')
    )
    op.create_index(op.f('ix_author_style_profiles_author_id'), 'author_style_profiles', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_style_profiles_id'), 'author_style_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_style_profiles_id'), table_name='author_style_profiles')
    op.drop_index(op.f('ix_author_style_profiles_author_id'), table_name='author_style_profiles')
    op.drop_table('author_style_profiles')
    # ### end Alembic commands ###
